//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopEngine.Frontend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopEngine.Frontend.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address delivery.
        /// </summary>
        internal static string AddressDelivery {
            get {
                return ResourceManager.GetString("AddressDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Specification.
        /// </summary>
        internal static string AddSpecification {
            get {
                return ResourceManager.GetString("AddSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add specification group.
        /// </summary>
        internal static string AddSpecificationGroup {
            get {
                return ResourceManager.GetString("AddSpecificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        internal static string BCC {
            get {
                return ResourceManager.GetString("BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories view.
        /// </summary>
        internal static string CategoriesView {
            get {
                return ResourceManager.GetString("CategoriesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the category?.
        /// </summary>
        internal static string CategoryDeletionConfirmation {
            get {
                return ResourceManager.GetString("CategoryDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Info.
        /// </summary>
        internal static string CategoryInfo {
            get {
                return ResourceManager.GetString("CategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification from linked categories.
        /// </summary>
        internal static string CategorySpecifications {
            get {
                return ResourceManager.GetString("CategorySpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category specification saved successfully.
        /// </summary>
        internal static string CategorySpecificationSaved {
            get {
                return ResourceManager.GetString("CategorySpecificationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create administrator.
        /// </summary>
        internal static string CreateAdministrator {
            get {
                return ResourceManager.GetString("CreateAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        internal static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Coupon.
        /// </summary>
        internal static string CreateCoupon {
            get {
                return ResourceManager.GetString("CreateCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create currency.
        /// </summary>
        internal static string CreateCurrency {
            get {
                return ResourceManager.GetString("CreateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create E-mail.
        /// </summary>
        internal static string CreateEmail {
            get {
                return ResourceManager.GetString("CreateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Gift Certificate.
        /// </summary>
        internal static string CreateGiftCertificate {
            get {
                return ResourceManager.GetString("CreateGiftCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order discount.
        /// </summary>
        internal static string CreateOrderDiscount {
            get {
                return ResourceManager.GetString("CreateOrderDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product discount.
        /// </summary>
        internal static string CreateProductDiscount {
            get {
                return ResourceManager.GetString("CreateProductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        internal static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user group.
        /// </summary>
        internal static string CreateUserGroup {
            get {
                return ResourceManager.GetString("CreateUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom product specifications.
        /// </summary>
        internal static string CustomProductSpecifications {
            get {
                return ResourceManager.GetString("CustomProductSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the category including all sub categories.
        /// </summary>
        internal static string DeleteAllSubCategories {
            get {
                return ResourceManager.GetString("DeleteAllSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        internal static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the category? Don&apos;t u ?.
        /// </summary>
        internal static string DeleteCategoryConfirmation {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the email? Don&apos;t u ?.
        /// </summary>
        internal static string DeleteEmailConfirmation {
            get {
                return ResourceManager.GetString("DeleteEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete only this category.
        /// </summary>
        internal static string DeleteOnlyThisCategory {
            get {
                return ResourceManager.GetString("DeleteOnlyThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductConfirmation.
        /// </summary>
        internal static string DeleteProductConfirmation {
            get {
                return ResourceManager.GetString("DeleteProductConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion options.
        /// </summary>
        internal static string DeletionOptions {
            get {
                return ResourceManager.GetString("DeletionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount value.
        /// </summary>
        internal static string DiscountValue {
            get {
                return ResourceManager.GetString("DiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying.
        /// </summary>
        internal static string Displaying {
            get {
                return ResourceManager.GetString("Displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit administrator.
        /// </summary>
        internal static string EditAdministrator {
            get {
                return ResourceManager.GetString("EditAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        internal static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user group.
        /// </summary>
        internal static string EditUserGroup {
            get {
                return ResourceManager.GetString("EditUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger for sendng the notification.
        /// </summary>
        internal static string EmailTriggerInfoDescription {
            get {
                return ResourceManager.GetString("EmailTriggerInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is in wrong format.
        /// </summary>
        internal static string EmailWrongFormat {
            get {
                return ResourceManager.GetString("EmailWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter body.
        /// </summary>
        internal static string EnterBody {
            get {
                return ResourceManager.GetString("EnterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category description.
        /// </summary>
        internal static string EnterCategoryDescription {
            get {
                return ResourceManager.GetString("EnterCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter category name.
        /// </summary>
        internal static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment for the status.
        /// </summary>
        internal static string EnterCommenForStatus {
            get {
                return ResourceManager.GetString("EnterCommenForStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer comment.
        /// </summary>
        internal static string EnterCustomerComment {
            get {
                return ResourceManager.GetString("EnterCustomerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer e-mail.
        /// </summary>
        internal static string EnterCustomerEmail {
            get {
                return ResourceManager.GetString("EnterCustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer name.
        /// </summary>
        internal static string EnterCustomerName {
            get {
                return ResourceManager.GetString("EnterCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer phone.
        /// </summary>
        internal static string EnterCustomerPhone {
            get {
                return ResourceManager.GetString("EnterCustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        internal static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        internal static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter house.
        /// </summary>
        internal static string EnterHouse {
            get {
                return ResourceManager.GetString("EnterHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID or name.
        /// </summary>
        internal static string EnterIdOrName {
            get {
                return ResourceManager.GetString("EnterIdOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        internal static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone.
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter postal code.
        /// </summary>
        internal static string EnterPostalCode {
            get {
                return ResourceManager.GetString("EnterPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product ID, title or SKU.
        /// </summary>
        internal static string EnterProductIdTitleSku {
            get {
                return ResourceManager.GetString("EnterProductIdTitleSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name.
        /// </summary>
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter related products group name.
        /// </summary>
        internal static string EnterRelatedProductsGroupName {
            get {
                return ResourceManager.GetString("EnterRelatedProductsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter relation name.
        /// </summary>
        internal static string EnterRelationName {
            get {
                return ResourceManager.GetString("EnterRelationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shipping address.
        /// </summary>
        internal static string EnterShippingAddress {
            get {
                return ResourceManager.GetString("EnterShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter SKU.
        /// </summary>
        internal static string EnterSku {
            get {
                return ResourceManager.GetString("EnterSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter specification group name.
        /// </summary>
        internal static string EnterSpecificationGroupName {
            get {
                return ResourceManager.GetString("EnterSpecificationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter specification name.
        /// </summary>
        internal static string EnterSpecificationName {
            get {
                return ResourceManager.GetString("EnterSpecificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter street.
        /// </summary>
        internal static string EnterStreet {
            get {
                return ResourceManager.GetString("EnterStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter subject.
        /// </summary>
        internal static string EnterSubject {
            get {
                return ResourceManager.GetString("EnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter title.
        /// </summary>
        internal static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user group name.
        /// </summary>
        internal static string EnterUserGroupName {
            get {
                return ResourceManager.GetString("EnterUserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export products.
        /// </summary>
        internal static string ExportProducts {
            get {
                return ResourceManager.GetString("ExportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string FirstNameIsRequired {
            get {
                return ResourceManager.GetString("FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed value.
        /// </summary>
        internal static string FixedValue {
            get {
                return ResourceManager.GetString("FixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found records.
        /// </summary>
        internal static string FoundRecords {
            get {
                return ResourceManager.GetString("FoundRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full name.
        /// </summary>
        internal static string FullNamePlaceholder {
            get {
                return ResourceManager.GetString("FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name is required.
        /// </summary>
        internal static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been successfully created.
        /// </summary>
        internal static string HasBeenSuccessfullyCreated {
            get {
                return ResourceManager.GetString("HasBeenSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been successfully deleted.
        /// </summary>
        internal static string HasBeenSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("HasBeenSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been successfully updated.
        /// </summary>
        internal static string HasBeenSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("HasBeenSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form has unsaved changes. Are you sure you want to continue?.
        /// </summary>
        internal static string HasUnsavedChangesConfirmation {
            get {
                return ResourceManager.GetString("HasUnsavedChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import products.
        /// </summary>
        internal static string ImportProducts {
            get {
                return ResourceManager.GetString("ImportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login date.
        /// </summary>
        internal static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotype.
        /// </summary>
        internal static string Logotype {
            get {
                return ResourceManager.GetString("Logotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage specification groups.
        /// </summary>
        internal static string ManageSpecificationGroups {
            get {
                return ResourceManager.GetString("ManageSpecificationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected specifications.
        /// </summary>
        internal static string MoveSelectedSpecifications {
            get {
                return ResourceManager.GetString("MoveSelectedSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected specifications to another group.
        /// </summary>
        internal static string MoveSelectedSpecificationsToAnotherGroup {
            get {
                return ResourceManager.GetString("MoveSelectedSpecificationsToAnotherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-line text.
        /// </summary>
        internal static string MultiLineText {
            get {
                return ResourceManager.GetString("MultiLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No administrators.
        /// </summary>
        internal static string NoAdministrators {
            get {
                return ResourceManager.GetString("NoAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available variables.
        /// </summary>
        internal static string NoAvailableVariables {
            get {
                return ResourceManager.GetString("NoAvailableVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories for now.
        /// </summary>
        internal static string NoCategories {
            get {
                return ResourceManager.GetString("NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No delivery.
        /// </summary>
        internal static string NoDelivery {
            get {
                return ResourceManager.GetString("NoDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No discounts.
        /// </summary>
        internal static string NoDiscounts {
            get {
                return ResourceManager.GetString("NoDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non registered user.
        /// </summary>
        internal static string NonRegisteredUser {
            get {
                return ResourceManager.GetString("NonRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product groups found.
        /// </summary>
        internal static string NoProductGroups {
            get {
                return ResourceManager.GetString("NoProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products.
        /// </summary>
        internal static string NoProducts {
            get {
                return ResourceManager.GetString("NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles.
        /// </summary>
        internal static string NoRoles {
            get {
                return ResourceManager.GetString("NoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specification groups added.
        /// </summary>
        internal static string NoSpecificationGroups {
            get {
                return ResourceManager.GetString("NoSpecificationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specifications added.
        /// </summary>
        internal static string NoSpecificationsAdded {
            get {
                return ResourceManager.GetString("NoSpecificationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specifications defined.
        /// </summary>
        internal static string NoSpecificationsDefined {
            get {
                return ResourceManager.GetString("NoSpecificationsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old price.
        /// </summary>
        internal static string OldPrice {
            get {
                return ResourceManager.GetString("OldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string OrderStatusCanceled {
            get {
                return ResourceManager.GetString("OrderStatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string OrderStatusComplete {
            get {
                return ResourceManager.GetString("OrderStatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string OrderStatusNew {
            get {
                return ResourceManager.GetString("OrderStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string OrderStatusPending {
            get {
                return ResourceManager.GetString("OrderStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string OrderStatusProcessing {
            get {
                return ResourceManager.GetString("OrderStatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoud it be replaced?.
        /// </summary>
        internal static string OrderTotalReplacementMessage {
            get {
                return ResourceManager.GetString("OrderTotalReplacementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored order total is different than the calculared one.
        /// </summary>
        internal static string OrderTotalViolationMessage {
            get {
                return ResourceManager.GetString("OrderTotalViolationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        internal static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category info.
        /// </summary>
        internal static string ProductCategoryInfo {
            get {
                return ResourceManager.GetString("ProductCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product group.
        /// </summary>
        internal static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product group creation.
        /// </summary>
        internal static string ProductGroupCreation {
            get {
                return ResourceManager.GetString("ProductGroupCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product group editing.
        /// </summary>
        internal static string ProductGroupEditing {
            get {
                return ResourceManager.GetString("ProductGroupEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string ProductGroupName {
            get {
                return ResourceManager.GetString("ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product groups.
        /// </summary>
        internal static string ProductGroups {
            get {
                return ResourceManager.GetString("ProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of products.
        /// </summary>
        internal static string ProductsCount {
            get {
                return ResourceManager.GetString("ProductsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivers.
        /// </summary>
        internal static string Receivers {
            get {
                return ResourceManager.GetString("Receivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered user.
        /// </summary>
        internal static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related product groups.
        /// </summary>
        internal static string RelatedProductGroups {
            get {
                return ResourceManager.GetString("RelatedProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the name.
        /// </summary>
        internal static string RequiredNameValidation {
            get {
                return ResourceManager.GetString("RequiredNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one value should be set.
        /// </summary>
        internal static string RequiredOptionsValidationMessage {
            get {
                return ResourceManager.GetString("RequiredOptionsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option value is required.
        /// </summary>
        internal static string RequiredOptionValidationMessage {
            get {
                return ResourceManager.GetString("RequiredOptionValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one role is required.
        /// </summary>
        internal static string RoleIsRequired {
            get {
                return ResourceManager.GetString("RoleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is required.
        /// </summary>
        internal static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select state.
        /// </summary>
        internal static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send E-mail.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of options (multiple).
        /// </summary>
        internal static string SetofMultipleOptions {
            get {
                return ResourceManager.GetString("SetofMultipleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of options (single).
        /// </summary>
        internal static string SetofSingleOptions {
            get {
                return ResourceManager.GetString("SetofSingleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set properties.
        /// </summary>
        internal static string SetProperties {
            get {
                return ResourceManager.GetString("SetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set specifications.
        /// </summary>
        internal static string SetSpecifications {
            get {
                return ResourceManager.GetString("SetSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set specification without group.
        /// </summary>
        internal static string SetSpecificationWithouGroup {
            get {
                return ResourceManager.GetString("SetSpecificationWithouGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set specification without group.
        /// </summary>
        internal static string SetSpecificationWithoutGroup {
            get {
                return ResourceManager.GetString("SetSpecificationWithoutGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value.
        /// </summary>
        internal static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on page.
        /// </summary>
        internal static string ShowOnPage {
            get {
                return ResourceManager.GetString("ShowOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-line text.
        /// </summary>
        internal static string SingleLineText {
            get {
                return ResourceManager.GetString("SingleLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku.
        /// </summary>
        internal static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification group is required.
        /// </summary>
        internal static string SpecificationGroupRequired {
            get {
                return ResourceManager.GetString("SpecificationGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification name.
        /// </summary>
        internal static string SpecificationName {
            get {
                return ResourceManager.GetString("SpecificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification value.
        /// </summary>
        internal static string SpecificationValue {
            get {
                return ResourceManager.GetString("SpecificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template variables.
        /// </summary>
        internal static string TemplateVariables {
            get {
                return ResourceManager.GetString("TemplateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put them into the e-mail body.
        /// </summary>
        internal static string TemplateVariablesDescription {
            get {
                return ResourceManager.GetString("TemplateVariablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon.
        /// </summary>
        internal static string TheCoupon {
            get {
                return ResourceManager.GetString("TheCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail.
        /// </summary>
        internal static string TheEmail {
            get {
                return ResourceManager.GetString("TheEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gift Certificate.
        /// </summary>
        internal static string TheGiftCertificate {
            get {
                return ResourceManager.GetString("TheGiftCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product.
        /// </summary>
        internal static string TheProduct {
            get {
                return ResourceManager.GetString("TheProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product discount.
        /// </summary>
        internal static string TheProductDiscount {
            get {
                return ResourceManager.GetString("TheProductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To_upper {
            get {
                return ResourceManager.GetString("To_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        internal static string UniqueNameValidation {
            get {
                return ResourceManager.GetString("UniqueNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User groups.
        /// </summary>
        internal static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info.
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name.
        /// </summary>
        internal static string ValidationRequiredProductName {
            get {
                return ResourceManager.GetString("ValidationRequiredProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product price.
        /// </summary>
        internal static string ValidationRequiredProductPrice {
            get {
                return ResourceManager.GetString("ValidationRequiredProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product SKU.
        /// </summary>
        internal static string ValidationRequiredProductSku {
            get {
                return ResourceManager.GetString("ValidationRequiredProductSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format value (use {value} variable).
        /// </summary>
        internal static string ValueFormatPlaceholder {
            get {
                return ResourceManager.GetString("ValueFormatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format should contain {value} marker.
        /// </summary>
        internal static string ValueFormatValidation {
            get {
                return ResourceManager.GetString("ValueFormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View administrator.
        /// </summary>
        internal static string ViewAdministrator {
            get {
                return ResourceManager.GetString("ViewAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Category.
        /// </summary>
        internal static string ViewCategory {
            get {
                return ResourceManager.GetString("ViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View process details.
        /// </summary>
        internal static string ViewProcessDetails {
            get {
                return ResourceManager.GetString("ViewProcessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Product.
        /// </summary>
        internal static string ViewProduct {
            get {
                return ResourceManager.GetString("ViewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Role.
        /// </summary>
        internal static string ViewRole {
            get {
                return ResourceManager.GetString("ViewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user.
        /// </summary>
        internal static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
